/**
 * band-tile-data.ts
 * Static metadata for the 15 spectrum band overlay tiles.
 * Each AllocationBox maps a labelled rect in the SVG viewBox (680×H)
 * to a tooltip. Hit areas are computed at render time as percentages.
 */

export interface AllocationBox {
  /** SVG viewBox x of the rect */
  x: number;
  /** SVG viewBox width of the rect */
  w: number;
  /** which row: 'top' = ACMA/BAND/BF-CAM/RADAR, 'bot' = NTIA/USE/RF-CAM */
  row: 'top' | 'bot';
  label: string;
  detail: string;
  colorHex: string;
}

export interface BandTile {
  id: string;
  /** path relative to /public */
  overlay: string;
  band: string;
  range: string;
  description: string;
  /** viewBox height — 230 or 240 */
  viewBoxH: number;
  /** top allocation row — y in viewBox */
  rowTopY: number;
  /** bottom allocation row — y in viewBox */
  rowBotY: number;
  /** height of each row */
  rowH: number;
  /** label shown in left gutter for top row */
  topLabel: string;
  /** label shown in left gutter for bottom row */
  botLabel: string;
  boxes: AllocationBox[];
}

/* ─── RF tiles — ACMA/NTIA rows at y=183/195, h=11 ─────────────────────── */

const VLF: BandTile = {
  id: 'vlf',
  overlay: '/spectrum/overlays/overlay-vlf.svg',
  band: 'VLF',
  range: '3 – 30 kHz',
  description: 'Submarine comms, strategic TACAMO',
  viewBoxH: 230,
  rowTopY: 183, rowBotY: 195, rowH: 11,
  topLabel: 'ACMA', botLabel: 'NTIA',
  boxes: [
    { x: 30, w: 620, row: 'top', label: 'MIL',
      detail: 'Military / RNS — VLF strategic submarine communications. TACAMO (E-6B Mercury), Harold Holt (NWC Exmouth), Jim Creek WA. Band penetrates seawater to ~20m depth.',
      colorHex: '#5B3A29' },
    { x: 30, w: 620, row: 'bot', label: 'GOV',
      detail: 'GOV — US/AUS/NATO strategic submarine comms. TACAMO continuity-of-comms relay, Harold Holt NWC 19.8 kHz, Jim Creek 24.8 kHz. Hardened against nuclear EMP.',
      colorHex: '#92400E' },
  ],
};

const LF: BandTile = {
  id: 'lf',
  overlay: '/spectrum/overlays/overlay-lf.svg',
  band: 'LF',
  range: '30 – 300 kHz',
  description: 'LORAN-C, DGPS beacons, military LF',
  viewBoxH: 230,
  rowTopY: 183, rowBotY: 195, rowH: 11,
  topLabel: 'ACMA', botLabel: 'NTIA',
  boxes: [
    { x: 30,  w: 138, row: 'top', label: 'MIL',
      detail: 'Military LF — submarine comms, low-frequency beacons 30–100 kHz. Long-range skywave propagation at night.',
      colorHex: '#5B3A29' },
    { x: 168, w: 46,  row: 'top', label: 'RNS',
      detail: 'Radio Navigation Service — LORAN-C 100 kHz chain navigation. 500–1000 nm range. Still active in some regions as GPS backup.',
      colorHex: '#4B1D96' },
    { x: 214, w: 398, row: 'top', label: 'FS',
      detail: 'Fixed Service — long-wave fixed point communications 100–285 kHz. NDB aviation beacons in lower portion.',
      colorHex: '#1C1917' },
    { x: 612, w: 38,  row: 'top', label: 'RNS',
      detail: 'RNS — DGPS differential correction beacons 285–325 kHz. Enhances GPS accuracy to <1m for maritime and coastal approach.',
      colorHex: '#4B1D96' },
    { x: 30,  w: 620, row: 'bot', label: 'GOV',
      detail: 'GOV — Government navigation infrastructure. LORAN-C (100 kHz) for long-range maritime/aviation nav. DGPS (285–325 kHz) coast-guard-operated correction beacons.',
      colorHex: '#92400E' },
  ],
};

const MF: BandTile = {
  id: 'mf',
  overlay: '/spectrum/overlays/overlay-mf.svg',
  band: 'MF',
  range: '300 – 3000 kHz',
  description: 'AM broadcast, maritime comms, NDB beacons',
  viewBoxH: 230,
  rowTopY: 183, rowBotY: 195, rowH: 11,
  topLabel: 'ACMA', botLabel: 'NTIA',
  boxes: [
    { x: 30,  w: 46,  row: 'top', label: 'ARN',
      detail: 'Aeronautical Radio Navigation — Non-Directional Beacons (NDB) 300–520 kHz. Used for instrument approaches and en-route navigation. Range 200–400 NM.',
      colorHex: '#7D1128' },
    { x: 76,  w: 115, row: 'top', label: 'MM',
      detail: 'Maritime Mobile — international distress 500 kHz (legacy), ship comms. 500 kHz was the global maritime distress frequency until superseded by GMDSS.',
      colorHex: '#164E63' },
    { x: 80,  w: 274, row: 'top', label: 'AM BCST',
      detail: 'AM Broadcast — 531–1602 kHz commercial AM band (9 kHz channel spacing ITU Region 3). Skywave propagation allows long-distance reception at night.',
      colorHex: '#78350F' },
    { x: 305, w: 345, row: 'top', label: 'MM',
      detail: 'Maritime Mobile — shore-to-ship comms 1600–3000 kHz. Distress/calling 2182 kHz (still monitored). Voice and CW maritime communications.',
      colorHex: '#164E63' },
    { x: 30,  w: 50,  row: 'bot', label: 'GOV',
      detail: 'GOV — Guard frequencies, military maritime beacon monitoring 300–520 kHz.',
      colorHex: '#92400E' },
    { x: 80,  w: 274, row: 'bot', label: 'NGV',
      detail: 'NGV — Commercial AM broadcast 531–1602 kHz. Non-government allocation.',
      colorHex: '#14532D' },
    { x: 354, w: 296, row: 'bot', label: 'GOV',
      detail: 'GOV — Military maritime/coastal guard 1600–3000 kHz. Monitoring of distress 2182 kHz. Navy coastal communication stations.',
      colorHex: '#92400E' },
  ],
};

const HF: BandTile = {
  id: 'hf',
  overlay: '/spectrum/overlays/overlay-hf.svg',
  band: 'HF',
  range: '3 – 30 MHz',
  description: 'HFGCS, OTH radar, NVIS tactical comms',
  viewBoxH: 230,
  rowTopY: 183, rowBotY: 195, rowH: 11,
  topLabel: 'ACMA', botLabel: 'NTIA',
  boxes: [
    { x: 30,  w: 46,  row: 'top', label: 'MIL',
      detail: 'Military HF — NVIS (Near Vertical Incidence Skywave) comms 3–5 MHz. Regional coverage 0–500 km with no dead zone. Tactical and strategic use.',
      colorHex: '#5B3A29' },
    { x: 76,  w: 69,  row: 'top', label: 'ARN',
      detail: 'Aeronautical Radio Navigation — HF aeronautical service 5–9 MHz. Long-range oceanic ATC comms, SELCAL. Airline HF comms on oceanic routes.',
      colorHex: '#7D1128' },
    { x: 145, w: 505, row: 'top', label: 'MIL / FS',
      detail: 'Military & Fixed Service — HFGCS (High Frequency Global Communications System) 9–30 MHz. Jindalee OTHR (8–30 MHz over-the-horizon radar, Alice Springs). NATO OTHR, broadcast jamming, skywave propagation 1000–5000 km.',
      colorHex: '#5B3A29' },
    { x: 30,  w: 620, row: 'bot', label: 'GOV',
      detail: 'GOV — Military HF: HFGCS strategic worldwide comms, Andover/Diego Garcia/Yokota relay stations. Jindalee OTHR surveillance of 37,000 km² of northern Australia.',
      colorHex: '#92400E' },
    { x: 76,  w: 69,  row: 'bot', label: 'SHR',
      detail: 'SHR — HF aeronautical shared civil/government. Airlines and military share the 5–9 MHz aeronautical HF bands.',
      colorHex: '#1E3A5F' },
  ],
};

const VHF: BandTile = {
  id: 'vhf',
  overlay: '/spectrum/overlays/overlay-vhf.svg',
  band: 'VHF',
  range: '30 – 300 MHz',
  description: 'SINCGARS tactical, VOR/ILS, maritime VHF',
  viewBoxH: 230,
  rowTopY: 183, rowBotY: 195, rowH: 11,
  topLabel: 'ACMA', botLabel: 'NTIA',
  boxes: [
    { x: 30,  w: 133, row: 'top', label: 'MIL',
      detail: 'Military VHF — SINCGARS FM tactical radio 30–88 MHz. Frequency-hopping 100 hops/sec. Ground-to-air, fire support, maneuver. Range ~20 km ground, ~100 km air-to-ground.',
      colorHex: '#5B3A29' },
    { x: 209, w: 67,  row: 'top', label: 'ARN',
      detail: 'Aeronautical Radio Navigation — VOR 108–118 MHz, ILS localizer 108–112 MHz, glide slope 329–335 MHz. ATC comms 118–137 MHz. Primary short-range navigation worldwide.',
      colorHex: '#7D1128' },
    { x: 292, w: 9,   row: 'top', label: 'ISM',
      detail: 'ISM — FM broadcast guard band. Industrial, Scientific and Medical use.',
      colorHex: '#374151' },
    { x: 319, w: 42,  row: 'top', label: 'MM',
      detail: 'Maritime Mobile — VHF channels 156–174 MHz. Channel 16 (156.8 MHz) international distress and calling. DSC automatic distress. AIS on Ch 87B/88B.',
      colorHex: '#164E63' },
    { x: 478, w: 172, row: 'top', label: 'MIL',
      detail: 'Military upper VHF — tactical datalink 225–400 MHz boundary. HAVE QUICK frequency-hopping ATC 225–400 MHz. Military radar boundary approaching UHF.',
      colorHex: '#5B3A29' },
    { x: 30,  w: 133, row: 'bot', label: 'GOV',
      detail: 'GOV — Military SINCGARS/tactical VHF 30–88 MHz. Army/USMC primary voice and data.',
      colorHex: '#92400E' },
    { x: 163, w: 46,  row: 'bot', label: 'NGV',
      detail: 'NGV — FM broadcast 88–108 MHz. Commercial, non-government.',
      colorHex: '#14532D' },
    { x: 209, w: 67,  row: 'bot', label: 'SHR',
      detail: 'SHR — Aeronautical VOR/ILS 108–137 MHz shared civil/government. Civil aviation primary nav with military use.',
      colorHex: '#1E3A5F' },
    { x: 361, w: 117, row: 'bot', label: 'NGV',
      detail: 'NGV — VHF TV broadcast boundary / land mobile 174–300 MHz. Commercial spectrum.',
      colorHex: '#14532D' },
    { x: 478, w: 172, row: 'bot', label: 'GOV',
      detail: 'GOV — Military upper VHF / HAVE QUICK frequency-hopping comms 225–400 MHz.',
      colorHex: '#92400E' },
  ],
};

const UHF: BandTile = {
  id: 'uhf',
  overlay: '/spectrum/overlays/overlay-uhf.svg',
  band: 'UHF',
  range: '300 MHz – 3 GHz',
  description: 'Link-16, IFF/Mode-S, GPS L-band, 4G/5G, FPV 2.4 GHz',
  viewBoxH: 230,
  rowTopY: 183, rowBotY: 195, rowH: 11,
  topLabel: 'ACMA', botLabel: 'NTIA',
  boxes: [
    { x: 30,  w: 23,  row: 'top', label: 'MIL',
      detail: 'Military UHF SATCOM — 300–400 MHz. Legacy UHF SATCOM (FLTSATCOM, LEASAT). Used by tactical ground and ship terminals.',
      colorHex: '#5B3A29' },
    { x: 56,  w: 8,   row: 'top', label: 'ISM 433',
      detail: 'ISM — 433.05–434.79 MHz. Industrial/scientific. FPV RC drone control (unlicensed), RFID, LoRa IoT. Range up to 2 km. Easily jammed.',
      colorHex: '#374151' },
    { x: 149, w: 58,  row: 'top', label: 'ARN / Link-16',
      detail: 'Aeronautical Radio Navigation — IFF Mode S transponders 1030/1090 MHz. Link-16 JTIDS/MIDS tactical datalink 960–1215 MHz. ADS-B 1090 MHz. Critical for beyond-visual-range SA.',
      colorHex: '#7D1128' },
    { x: 207, w: 42,  row: 'top', label: 'RNS / GNSS',
      detail: 'RNS — GNSS L-band 1215–1400 MHz. GPS L2 (1227.6 MHz), L5 (1176.45 MHz), GLONASS L2 (1246 MHz), Galileo E5 (1191.8 MHz). Protected navigation spectrum.',
      colorHex: '#4B1D96' },
    { x: 249, w: 69,  row: 'top', label: 'MM / Met',
      detail: 'Maritime Mobile / Meteorological — S-band weather radar 2.7–3 GHz, met aids. Passive EESS 1400–1427 MHz (radiotelescopes / soil moisture satellites).',
      colorHex: '#164E63' },
    { x: 318, w: 186, row: 'top', label: 'Cellular',
      detail: 'Mobile — 4G LTE / 5G NR cellular 1.7–2.7 GHz. LTE Bands 1/3/7/25. 5G Sub-6 GHz. Used by commercial drones for C2 link and swarm coordination via LTE.',
      colorHex: '#164E63' },
    { x: 504, w: 23,  row: 'top', label: 'ISM 2.4G',
      detail: 'ISM — 2400–2483.5 MHz. Wi-Fi, Bluetooth, FPV drone 2.4 GHz RC link. DJI default control frequency. Extremely congested in urban environments. Easy to detect and jam.',
      colorHex: '#374151' },
    { x: 527, w: 123, row: 'top', label: 'SAT / S-band',
      detail: 'Satellite / SHF boundary — S-band radar 2.5–3 GHz, SATCOM uplinks. Weather radar, ship radar, military search radar at upper end.',
      colorHex: '#1E1B4B' },
    { x: 30,  w: 23,  row: 'bot', label: 'GOV',
      detail: 'GOV — Military UHF SATCOM 300–400 MHz. DoD fleet comms, submarine comms.',
      colorHex: '#92400E' },
    { x: 53,  w: 96,  row: 'bot', label: 'SHR',
      detail: 'SHR — UHF TV / land mobile 400–960 MHz. Mix of government and commercial mobile.',
      colorHex: '#1E3A5F' },
    { x: 149, w: 58,  row: 'bot', label: 'SHR ARN',
      detail: 'SHR — Link-16 / IFF 960–1215 MHz shared civil aviation and military.',
      colorHex: '#1E3A5F' },
    { x: 207, w: 42,  row: 'bot', label: 'GOV GNSS',
      detail: 'GOV — GNSS L-band protected 1215–1400 MHz. ITU protected allocation for navigation satellites.',
      colorHex: '#92400E' },
    { x: 318, w: 332, row: 'bot', label: 'NGV / 5G',
      detail: 'NGV — Commercial 4G/5G cellular 1.7–3 GHz. Non-government mobile broadband.',
      colorHex: '#14532D' },
  ],
};

const SHF: BandTile = {
  id: 'shf',
  overlay: '/spectrum/overlays/overlay-shf.svg',
  band: 'SHF',
  range: '3 – 30 GHz',
  description: 'Ku/Ka SATCOM, X-band SAR, Starlink, military radar',
  viewBoxH: 230,
  rowTopY: 183, rowBotY: 195, rowH: 11,
  topLabel: 'ACMA', botLabel: 'NTIA',
  boxes: [
    { x: 30,  w: 46,  row: 'top', label: 'MIL S-band',
      detail: 'Military SHF S-band — tactical radar 2.9–3.7 GHz. Ship search radar, ground-based AD acquisition radar. Weather radar at 2.7–2.9 GHz.',
      colorHex: '#5B3A29' },
    { x: 76,  w: 70,  row: 'top', label: 'SAT C-band',
      detail: 'Satellite C-band — SATCOM uplink 5.85–6.425 GHz, downlink 3.4–4.2 GHz. Highly weather-resistant. Intel/milsatcom on hardened C-band terminals.',
      colorHex: '#1E1B4B' },
    { x: 146, w: 92,  row: 'top', label: 'MIL X-band',
      detail: 'Military X-band — fire control 8.5–10.55 GHz, SAR imagery, APG-81/AESA. X-band SAR: 1m resolution at 600 km altitude. Patriot FCR, Aegis SPY-1 at X/S.',
      colorHex: '#5B3A29' },
    { x: 238, w: 138, row: 'top', label: 'SAT Ku',
      detail: 'Satellite Ku-band — SATCOM uplink 14–14.5 GHz, downlink 10.7–12.75 GHz. WGS (Wideband Global SATCOM). Commercial VSAT. Starlink user terminals at Ku. High bandwidth, affected by rain.',
      colorHex: '#1E1B4B' },
    { x: 536, w: 114, row: 'top', label: 'SAT Ka',
      detail: 'Satellite Ka-band — high-throughput SATCOM 26.5–40 GHz. Starlink downlink 10.7–12.7 GHz (Ku) and 17.8–18.6 GHz (Ka). WGS Ka: 8.1 Gbps/satellite. Severe rain fade above 30 GHz.',
      colorHex: '#1E1B4B' },
    { x: 30,  w: 345, row: 'bot', label: 'GOV',
      detail: 'GOV — Military radar and SATCOM 3–15 GHz. S/C/X-band tactical radar, naval surface search, SATCOM terminals.',
      colorHex: '#92400E' },
    { x: 375, w: 127, row: 'bot', label: 'SHR Ku',
      detail: 'SHR — Ku-band commercial/military SATCOM shared. Commercial FSS satellites share spectrum with military Ku uplinks.',
      colorHex: '#1E3A5F' },
    { x: 502, w: 148, row: 'bot', label: 'GOV Ka',
      detail: 'GOV — Ka-band military SATCOM 26.5–40 GHz. WGS (Wideband Global SATCOM) Ka-band high-capacity relay for UAV ISR, C2, intel.',
      colorHex: '#92400E' },
  ],
};

const EHF: BandTile = {
  id: 'ehf',
  overlay: '/spectrum/overlays/overlay-ehf.svg',
  band: 'EHF',
  range: '30 – 300 GHz',
  description: 'AEHF protected SATCOM, mmWave, W-band radar',
  viewBoxH: 230,
  rowTopY: 183, rowBotY: 195, rowH: 11,
  topLabel: 'ACMA', botLabel: 'NTIA',
  boxes: [
    { x: 30,  w: 69,  row: 'top', label: 'MIL AEHF',
      detail: 'Military EHF — AEHF (Advanced Extremely High Frequency) 44 GHz uplink / 20 GHz downlink. Nuclear-hardened, jam-resistant protected SATCOM. 6 Mbps per user vs MILSTAR 75 kbps. Replaces MILSTAR.',
      colorHex: '#5B3A29' },
    { x: 90,  w: 18,  row: 'top', label: 'ISM 60G',
      detail: 'ISM — 57–66 GHz. 60 GHz Wi-Fi / WiGig (802.11ad/ay). Oxygen absorption ~10 dB/km creates natural security zone — signal dies within 100m.',
      colorHex: '#374151' },
    { x: 108, w: 77,  row: 'top', label: 'SAT W-band',
      detail: 'Satellite W-band — EHF SATCOM, space research 65–100 GHz. W-band automotive radar 76–81 GHz (3GPP). Emerging high-capacity milsatcom.',
      colorHex: '#1E1B4B' },
    { x: 185, w: 465, row: 'top', label: 'Research / FS',
      detail: 'Fixed Service / Research — atmospheric sensing, radio astronomy, emerging mmWave 5G (above 100 GHz), sub-THz imaging and comms. Largely undeveloped below 300 GHz.',
      colorHex: '#1C1917' },
    { x: 30,  w: 69,  row: 'bot', label: 'GOV AEHF',
      detail: 'GOV — AEHF protected military SATCOM 30–60 GHz. US/UK/Canada/Netherlands. Nuclear EMP survivable. Anti-jam LPI/LPD.',
      colorHex: '#92400E' },
    { x: 90,  w: 27,  row: 'bot', label: 'SHR 60G',
      detail: 'SHR — 57–66 GHz shared ISM and fixed wireless. Limited range due to O₂ absorption.',
      colorHex: '#1E3A5F' },
    { x: 113, w: 69,  row: 'bot', label: 'GOV W-band',
      detail: 'GOV — Military W-band radar 76–81 GHz, auto/vehicular radar. Emerging EHF SATCOM research.',
      colorHex: '#92400E' },
    { x: 182, w: 468, row: 'bot', label: 'SHN Emerging',
      detail: 'SHN — Emerging mmWave applications: 5G NR FR2 above 100 GHz, atmospheric sensing, space research, sub-THz imaging systems.',
      colorHex: '#1A3A2A' },
  ],
};

/* ─── GNSS tile — allocation bars at y=215/223, h=8 (L2 inset panel above) */

const GNSS: BandTile = {
  id: 'gnss',
  overlay: '/spectrum/overlays/overlay-gnss.svg',
  band: 'GNSS',
  range: '1100 – 1700 MHz',
  description: 'GPS/GLONASS/Galileo/BeiDou L-band detail',
  viewBoxH: 230,
  rowTopY: 215, rowBotY: 223, rowH: 8,
  topLabel: 'ACMA', botLabel: 'NTIA',
  boxes: [
    { x: 30, w: 620, row: 'top', label: 'RNS',
      detail: 'Radio Navigation Service — full GNSS L-band protected allocation 1100–1700 MHz. GPS L1 (1575.42), L2 (1227.6), L5 (1176.45); GLONASS L1/L2; Galileo E1/E5/E6; BeiDou B1/B2/B3. ITU protected — jamming is internationally illegal.',
      colorHex: '#4B1D96' },
    { x: 30, w: 620, row: 'bot', label: 'GOV',
      detail: 'GOV — GNSS spectrum protected for all navigation satellite services. US Space Force GPS, Russian GLONASS, EU Galileo, Chinese BeiDou. PNT backbone for all precision-guided munitions.',
      colorHex: '#92400E' },
  ],
};

/* ─── Optical / Radar tiles — BAND/USE rows at y=180/194, h=13 ───────────── */

const IR: BandTile = {
  id: 'ir',
  overlay: '/spectrum/overlays/overlay-ir.svg',
  band: 'IR',
  range: '1mm – 700nm',
  description: 'FLIR, missile seekers, Javelin/Hellfire, MANPADS',
  viewBoxH: 240,
  rowTopY: 180, rowBotY: 194, rowH: 13,
  topLabel: 'BAND', botLabel: 'USE',
  boxes: [
    { x: 30,  w: 358, row: 'top', label: 'FIR >15μm',
      detail: 'Far Infrared >15μm — Terahertz / atmospheric thermal emission. Passive surveillance, atmospheric CO₂/H₂O absorption bands, submm communications research.',
      colorHex: '#1E1B4B' },
    { x: 388, w: 54,  row: 'top', label: 'LWIR 8–15μm',
      detail: 'Long-Wave IR 8–15μm — Atmospheric transmission window. Best thermal contrast for FLIR (forward-looking infrared). Stinger/Igla MANPADS seekers. Passive, all-weather.',
      colorHex: '#4C1D95' },
    { x: 442, w: 84,  row: 'top', label: 'MWIR 3–8μm',
      detail: 'Mid-Wave IR 3–8μm — Hot-metal signatures: turbine exhaust, rocket plume. Javelin, Hellfire, MANPADS (Igla/Stinger) seeker band. Requires cryogenic cooling for best sensitivity.',
      colorHex: '#7F1D1D' },
    { x: 526, w: 65,  row: 'top', label: 'SWIR / Laser',
      detail: 'Short-Wave IR 1.4–3μm — Nd:YAG laser designation 1.064μm (eye-safe ~1.5μm). Backreflection from laser-designated targets. SWIR cameras for night vision + laser spot.',
      colorHex: '#78350F' },
    { x: 591, w: 59,  row: 'top', label: 'NIR / CCD',
      detail: 'Near IR 0.7–1.4μm — Silicon CCD/CMOS detector range. Invisible to human eye. Night-vision with IR illuminators, Nd:YAG target marking at 1.064μm.',
      colorHex: '#064E3B' },
    { x: 30,  w: 358, row: 'bot', label: 'Atm. thermal',
      detail: 'Atmospheric thermal emission — Terahertz systems, far-IR sensors. Limited by atmosphere — primary use in airborne or space-based sensors.',
      colorHex: '#0F0F1A' },
    { x: 388, w: 54,  row: 'bot', label: 'FLIR / Stinger',
      detail: 'FLIR sensors (LWIR window), Stinger seeker (IIR upgrade), Igla-S IR seeker. Uncooled microbolometer detectors adequate for most platforms.',
      colorHex: '#2E1065' },
    { x: 442, w: 84,  row: 'bot', label: 'Javelin / Hellfire',
      detail: 'Javelin (CLU + seeker MWIR), AGM-114 Hellfire, Igla/Igla-S MANPADS. Imaging infrared seeker for terminal guidance. Cooled InSb or HgCdTe detector.',
      colorHex: '#450A0A' },
    { x: 526, w: 65,  row: 'bot', label: 'Nd:YAG / eye-safe',
      detail: 'Nd:YAG 1.064μm target designation (Paveway, JDAM-ER IR variant), eye-safe 1.5μm laser rangefinders and designators. SWIR camera for designation confirmation.',
      colorHex: '#451A03' },
    { x: 591, w: 59,  row: 'bot', label: 'NV / CCD cam',
      detail: 'Intensified CCD night-vision (I²) and silicon CCD/CMOS EO cameras. Standard ISR payload for MQ-9, TB-2 MX-15D. Gated ICCD for range-finding.',
      colorHex: '#022C22' },
  ],
};

const VIS: BandTile = {
  id: 'visible',
  overlay: '/spectrum/overlays/overlay-visible.svg',
  band: 'Visible',
  range: '380 – 780nm',
  description: 'EO cameras, FPV, MQ-9 MTS-B, TB-2 MX-15D',
  viewBoxH: 230,
  rowTopY: 180, rowBotY: 192, rowH: 12,
  topLabel: 'BF CAM', botLabel: 'RF CAM',
  boxes: [
    { x: 139, w: 511, row: 'top', label: 'MQ-9 MTS-B',
      detail: 'MQ-9 Reaper Multi-Spectral Targeting System (MTS-B) — EO + NIR 450–900nm. Provides day/night ISR and laser designation. Range >40 km slant at altitude.',
      colorHex: '#1E3A8A' },
    { x: 92,  w: 435, row: 'top', label: 'TB-2 MX-15D',
      detail: 'Bayraktar TB-2 — Wescam MX-15D EO/IR turret 420–700nm visible band. Full-colour day camera + LWIR FLIR + laser designator. Proved decisive over Nagorno-Karabakh, Ukraine.',
      colorHex: '#065F46' },
    { x: 30,  w: 497, row: 'bot', label: 'FPV 380–700nm',
      detail: 'FPV (First Person View) drone — standard CMOS camera 380–700nm visible. Commercial cameras (GoPro, RunCam). Primary attack/recon platform Ukraine 2022–2025. Unencrypted 5.8 GHz video link.',
      colorHex: '#7F1D1D' },
    { x: 30,  w: 620, row: 'bot', label: 'Shahed-136',
      detail: 'Shahed-136 Geranium-2 — optical navigation aids 380–780nm full visible spectrum. Primarily INS+GPS guided with visual terrain correlation for terminal. No IR seeker.',
      colorHex: '#7F1D1D' },
  ],
};

const UV: BandTile = {
  id: 'uv',
  overlay: '/spectrum/overlays/overlay-uv.svg',
  band: 'UV',
  range: '400 – 10nm',
  description: 'Solar-blind seekers, plume detection, bio-agents',
  viewBoxH: 240,
  rowTopY: 180, rowBotY: 194, rowH: 13,
  topLabel: 'BAND', botLabel: 'USE',
  boxes: [
    { x: 30,  w: 136, row: 'top', label: 'UVA 315–400nm',
      detail: 'UVA 315–400nm — "black light". UV missile warning systems (US-AN/AAR-47, Russian L-136). Plume and flame detection. Solar-reflected signal still present.',
      colorHex: '#3B1D8A' },
    { x: 166, w: 53,  row: 'top', label: 'UVB 280–315nm',
      detail: 'UVB 280–315nm — partial atmospheric absorption. Sunburn wavelengths. Limited defence applications. UV-B spectroscopy for biological agent detection.',
      colorHex: '#4C1D96' },
    { x: 219, w: 149, row: 'top', label: 'UVC 200–280nm',
      detail: 'UVC 200–280nm — heavily absorbed by ozone layer. "Solar blind" window: terrestrial background ~0. Used in solar-blind missile seekers (UV MANPADS warning). Germicidal (254nm).',
      colorHex: '#5B21B6' },
    { x: 368, w: 159, row: 'top', label: 'VUV 100–200nm',
      detail: 'Vacuum UV 100–200nm — absorbed by air within metres. Lab and space use only. EUV lithography (193nm ArF laser, 13.5nm EUV). No atmospheric propagation.',
      colorHex: '#6D28D9' },
    { x: 527, w: 123, row: 'top', label: 'EUV 10–100nm',
      detail: 'Extreme UV 10–100nm — absorbed by all matter in air. ASML EUV chip lithography (13.5nm). Space telescope observation only. No conventional weapons application.',
      colorHex: '#7C3AED' },
    { x: 30,  w: 136, row: 'bot', label: 'UV MWS / plume',
      detail: 'UV Missile Warning Systems: AN/AAR-47, MAWS on F-35 (AN/AAQ-37). Plume detection from rocket motors. Solar-reflected UV provides background in UVA.',
      colorHex: '#1E1040' },
    { x: 166, w: 53,  row: 'bot', label: 'Sunburn / bio',
      detail: 'UVB bioagent detection — some biological agents fluoresce under UVB. Tactical bio-sensor use. Sunburn / human health hazard at high intensity.',
      colorHex: '#200E4A' },
    { x: 219, w: 149, row: 'bot', label: 'Solar-blind seeker',
      detail: 'Solar-blind UV seeker — zero solar background in UVC allows very sensitive rocket plume detection. AN/AAR-47 upgrade, Mirage 2000 SPIRALE MAWS. Germicidal at 254nm.',
      colorHex: '#280E5A' },
    { x: 368, w: 159, row: 'bot', label: 'Lab / space only',
      detail: 'Absorbed by atmosphere within metres. No battlefield propagation. Laboratory spectroscopy, space physics, EUV lithography.',
      colorHex: '#30106A' },
    { x: 527, w: 123, row: 'bot', label: 'EUV lithography',
      detail: 'ASML EUV semiconductor lithography 13.5nm. Space telescope observation. No conventional applications in atmosphere.',
      colorHex: '#3B127A' },
  ],
};

const DEW: BandTile = {
  id: 'dew',
  overlay: '/spectrum/overlays/overlay-dew.svg',
  band: 'Laser / DEW',
  range: '20μm – 350nm',
  description: 'HELIOS, Iron Beam, DRAGONFIRE, DIRCM, GLARE (log wavelength)',
  viewBoxH: 240,
  rowTopY: 180, rowBotY: 194, rowH: 13,
  topLabel: 'BAND', botLabel: 'USE',
  boxes: [
    { x: 30,  w: 140, row: 'top', label: 'CO₂ LWIR  10.6μm',
      detail: 'CO₂ laser zone 8–20μm. MIRACL (2.2 MW) and THEL (tactical HEL) operated in this band. High atmospheric absorption outside 8–14μm window limits engagement range.',
      colorHex: '#1E1B4B' },
    { x: 170, w: 151, row: 'top', label: 'MWIR  3–8μm — DIRCM',
      detail: 'Mid-wave IR 3–8μm — MANPADS seeker band. DIRCM (Directional IR Countermeasure): CIRCM, Guardian, LAIRCM. Jamming SA-7/14/16/24 Igla-S seekers with modulated IR. Missile approach warning at this band.',
      colorHex: '#064E3B' },
    { x: 321, w: 101, row: 'top', label: 'SWIR eye-safe',
      detail: 'Short-wave IR 1.5–3μm — eye-safe laser range-finding and designation. Avoids 1.06μm Nd:YAG eye damage risk. Also laser communication systems and SWIR EO cameras for night ISR.',
      colorHex: '#3B0764' },
    { x: 422, w: 121, row: 'top', label: 'NIR / 1μm HEL',
      detail: 'Fibre laser and Nd:YAG zone 0.7–1.5μm. Primary wavelength for modern high-energy lasers: HELIOS 60 kW, Iron Beam 100 kW, SHiELD, DRAGONFIRE 50 kW. Near-zero atmospheric absorption, excellent beam quality.',
      colorHex: '#4C1D95' },
    { x: 543, w: 107, row: 'top', label: 'VIS dazzle',
      detail: 'Visible spectrum 0.35–0.7μm — laser dazzlers and blinding weapons. GLARE MOUT green 0.532μm Nd:YAG (eye-safe power), JLENS, vehicle checkpoint denial. Regulated under Protocol IV CCW.',
      colorHex: '#78350F' },
    { x: 30,  w: 140, row: 'bot', label: 'MIRACL / THEL (legacy)',
      detail: 'Mid-Infrared Advanced Chemical Laser (MIRACL) 2.2 MW at 3.8μm deuterium-fluoride. THEL (Tactical HEL) for Katyusha/mortar intercept trials 2000–2004. CO₂ gas dynamic laser 10.6μm HELIOS prototype.',
      colorHex: '#0F0F1A' },
    { x: 170, w: 151, row: 'bot', label: 'DIRCM / CIRCM MANPADS defeat',
      detail: 'Directional IR Countermeasure — CIRCM (Common IRCM), AN/AAQ-24 Nemesis, Guardian (Boeing 767/747 program). Steerable IR source jams heat-seeking missile seekers. Defeats Igla/Stinger MANPADS.',
      colorHex: '#022C22' },
    { x: 321, w: 101, row: 'bot', label: 'Eye-safe LRF / comms',
      detail: 'Eye-safe laser rangefinders and target designators at 1.54–1.57μm (Er:glass, Raman-shifted). Laser comms (LLCD demonstrated 622 Mbps space-to-ground). SWIR cameras as NV aid.',
      colorHex: '#1A0A30' },
    { x: 422, w: 121, row: 'bot', label: 'HELIOS · Iron Beam · SHiELD',
      detail: 'HELIOS (AN/SEQ-3) USN 60 kW fiber laser, Iron Beam (Rafael) 100 kW operational Israel, SHiELD USAF airborne DEW pod, ATHENA 60 kW ground demo, HELWS-MRZR 15 kW vehicle, DRAGONFIRE UK 50 kW. All ≈1.07μm fiber laser.',
      colorHex: '#2E1065' },
    { x: 543, w: 107, row: 'bot', label: 'GLARE dazzler',
      detail: 'GLARE MOUT 0.532μm green Nd:YAG dazzler for vehicle checkpoints and crowd control. Temporarily blinds at safe standoff. Regulated by Protocol IV CCW (prohibited if designed to cause permanent blindness).',
      colorHex: '#451A03' },
  ],
};

const XRAY: BandTile = {
  id: 'xray',
  overlay: '/spectrum/overlays/overlay-xray.svg',
  band: 'X-ray',
  range: '10 – 0.01nm',
  description: 'Nuclear detection, CT imaging, CBRN sensors',
  viewBoxH: 240,
  rowTopY: 180, rowBotY: 194, rowH: 13,
  topLabel: 'BAND', botLabel: 'USE',
  boxes: [
    { x: 30,  w: 413, row: 'top', label: 'Soft X-ray 0.1–10nm',
      detail: 'Soft X-ray 0.1–10nm — synchrotron sources, EUV boundary. Plasma physics, astronomical observation. Absorbed by air at sea level within metres.',
      colorHex: '#1E3A5F' },
    { x: 443, w: 207, row: 'top', label: 'Hard X-ray 0.01–0.1nm',
      detail: 'Hard X-ray 0.01–0.1nm — penetrating radiation. Medical CT (0.05–0.01nm), industrial NDT, nuclear material detection. Compton scattering and photoelectric effect.',
      colorHex: '#3B0764' },
    { x: 30,  w: 413, row: 'bot', label: 'Synchrotron / EUV',
      detail: 'Synchrotron radiation sources, EUV lithography (13.5nm), X-ray astronomy, plasma physics research. Extremely energetic photons, air-absorbing.',
      colorHex: '#0F1A2E' },
    { x: 443, w: 207, row: 'bot', label: 'CT / NDT / CBRN',
      detail: 'Medical CT and fluoroscopy, industrial non-destructive testing, nuclear material detection for CBRN, airport baggage/cargo X-ray scanners. SNM (Special Nuclear Material) detection.',
      colorHex: '#1A0030' },
  ],
};

const GAMMA: BandTile = {
  id: 'gamma',
  overlay: '/spectrum/overlays/overlay-gamma.svg',
  band: 'Gamma',
  range: '10 – 0.001pm',
  description: 'Nuclear detection, CBRN payload, PET/SPECT',
  viewBoxH: 240,
  rowTopY: 180, rowBotY: 194, rowH: 13,
  topLabel: 'BAND', botLabel: 'USE',
  boxes: [
    { x: 30,  w: 155, row: 'top', label: 'Low γ 10–1pm',
      detail: 'Low gamma 10–1pm — nuclear medicine isotopes (Tc-99m 0.14 MeV, I-131). SNM detection (Cs-137, Co-60). PET/SPECT imaging. Passive radiation detection for CBRN.',
      colorHex: '#2E1065' },
    { x: 185, w: 155, row: 'top', label: 'Mid γ 1–0.1pm',
      detail: 'Mid gamma 1–0.1pm — high-energy nuclear transitions. Gamma spectroscopy for isotope ID. Reactor safety monitoring. U-235, Pu-239 signatures.',
      colorHex: '#3B0764' },
    { x: 340, w: 155, row: 'top', label: 'High γ 0.1–0.01pm',
      detail: 'High gamma 0.1–0.01pm — particle accelerator byproduct. Pair production dominant. Extreme radiation hazard. Shielding: >50mm lead or equivalent.',
      colorHex: '#4C0882' },
    { x: 495, w: 155, row: 'top', label: 'Cosmic / UHE γ',
      detail: 'Cosmic gamma-rays — ultra-high energy from pulsars, blazars, GRBs. Detected only by space observatories (Fermi LAT). No atmospheric propagation to ground.',
      colorHex: '#581C87' },
    { x: 30,  w: 155, row: 'bot', label: 'Nuclear medicine',
      detail: 'Nuclear medicine (PET/SPECT), SNM detection (Special Nuclear Material), dirty bomb material identification. RADIAC instruments, portal monitors, backpack detectors.',
      colorHex: '#1A0A30' },
    { x: 185, w: 155, row: 'bot', label: 'Spectroscopy / reactor',
      detail: 'Gamma spectroscopy for isotope fingerprinting, reactor safety, environmental monitoring. HPGe detectors for field isotope ID. IAEA safeguards.',
      colorHex: '#200B38' },
    { x: 340, w: 155, row: 'bot', label: 'Accelerator / CBRN',
      detail: 'Particle accelerator byproduct, CBRN detection high-energy gamma. Compton imaging for source localisation. Shielded transport of radioactive material.',
      colorHex: '#280D42' },
    { x: 495, w: 155, row: 'bot', label: 'Cosmic ray obs.',
      detail: 'Cosmic ray observatories (Auger, MAGIC, CTA), space-based gamma telescopes (Fermi, INTEGRAL). No ground-level propagation — astrophysics only.',
      colorHex: '#30104C' },
  ],
};

const RADAR: BandTile = {
  id: 'radar',
  overlay: '/spectrum/overlays/overlay-radar.svg',
  band: 'Radar',
  range: '0.23 – 110 GHz',
  description: 'IEEE radar bands — OTH to W-band C-UAS',
  viewBoxH: 240,
  rowTopY: 180, rowBotY: 193, rowH: 12,
  topLabel: 'RADAR', botLabel: 'USE',
  boxes: [
    { x: 30,  w: 148, row: 'top', label: 'P/UHF — EW/OTH',
      detail: 'P-band (0.23–1 GHz) / UHF — EW surveillance, OTH radar, ballistic missile early warning. Nebo-M (multi-band VHF/UHF), Struna passive detection. Penetrates foliage and some stealth coatings.',
      colorHex: '#134E4A' },
    { x: 178, w: 69,  row: 'top', label: 'L — ATC/Acq',
      detail: 'L-band (1–2 GHz) — ATC surveillance, ARSR long-range search, SAM acquisition. S-300/400 acquisition radar 76N6 Clam Shell. ADS-B 1090 MHz. Long range 400+ km.',
      colorHex: '#164E63' },
    { x: 247, w: 70,  row: 'top', label: 'S — Search/Wx',
      detail: 'S-band (2–4 GHz) — weather radar, ship search, medium-range SAM fire control. 9K317 Buk fire control 9S36. Sentinel C-UAS detection radar. AN/MPQ-64F1.',
      colorHex: '#1E3A8A' },
    { x: 317, w: 69,  row: 'top', label: 'C — Tac/Ship',
      detail: 'C-band (4–8 GHz) — tactical fire control, ship navigation, NATO HAWK (AN/MPQ-57). Weather radar Doppler. Compact shipborne search and FC radar.',
      colorHex: '#1E40AF' },
    { x: 386, w: 41,  row: 'top', label: 'X — FC/SAR',
      detail: 'X-band (8–12 GHz) — fire control, SAR imagery, airborne radar. APG-81 (F-35), APG-79 (F/A-18E/F), Piaggio Astore SAR. Patriot FCR AN/MPQ-65. Most widely used military radar band.',
      colorHex: '#4C1D95' },
    { x: 427, w: 41,  row: 'top', label: 'Ku — SAR',
      detail: 'Ku-band (12–18 GHz) — high-resolution SAR, JSTARS MTI, MQ-9 Lynx SAR. Fine angular resolution. Rain-limited for long range.',
      colorHex: '#6D28D9' },
    { x: 468, w: 39,  row: 'top', label: 'K — (attenuated)',
      detail: 'K-band (18–27 GHz) — heavily attenuated by water vapour absorption at 22 GHz. Rarely used for radar. Police speed guns at 24.125 GHz.',
      colorHex: '#374151' },
    { x: 507, w: 41,  row: 'top', label: 'Ka — C-UAS',
      detail: 'Ka-band (27–40 GHz) — counter-UAS radar (DroneShield DroneSentinel, Fortem TrueView). High angular resolution, compact antenna. SkyDome C-UAS system.',
      colorHex: '#7C3AED' },
    { x: 548, w: 63,  row: 'top', label: 'V — mmWave',
      detail: 'V-band (40–75 GHz) — millimetre-wave. 60 GHz Wi-Fi, short-range high-bandwidth comms. Point-to-point backhaul. Oxygen absorption at 60 GHz limits range to ~1 km.',
      colorHex: '#831843' },
    { x: 611, w: 39,  row: 'top', label: 'W — auto/exp',
      detail: 'W-band (75–110 GHz) — automotive collision-avoidance radar (76–81 GHz). Experimental high-resolution imaging. Compact size for airborne applications.',
      colorHex: '#9D174D' },
    { x: 30,  w: 148, row: 'bot', label: 'Nebo-M / BMEWS',
      detail: 'Nebo-M multi-frequency (VHF+UHF), Struna-1 passive bistatic (100–300 MHz), BMEWS ballistic missile early warning. P-band penetrates RAS stealth to a degree.',
      colorHex: '#0A1F1C' },
    { x: 178, w: 69,  row: 'bot', label: '76N6 / S-300 acq',
      detail: '76N6 Clam Shell S-300 acquisition radar, P-18 Spoon Rest, ASR-11 ATC. Long-range volume search.',
      colorHex: '#0C1F26' },
    { x: 247, w: 70,  row: 'bot', label: 'Sentinel / Buk-M2',
      detail: 'AN/MPQ-64F1 Sentinel (army AD C-UAS search), 9S36 Buk-M2 fire control. Weather radar (WSR-88D NEXRAD).',
      colorHex: '#0C1527' },
    { x: 317, w: 69,  row: 'bot', label: 'Ship FC / SAR',
      detail: 'Ship fire control radar, SAR imagery, HAWK SAM FC. C-band compact shipborne multi-mode.',
      colorHex: '#0A1530' },
    { x: 386, w: 41,  row: 'bot', label: 'APG-81 / APG-79',
      detail: 'APG-81 AESA (F-35A/B/C), APG-79 AESA (F/A-18E/F Super Hornet), Patriot AN/MPQ-65. Most capable fire-control band.',
      colorHex: '#1C0A3F' },
    { x: 427, w: 41,  row: 'bot', label: 'JSTARS / SAR hi-res',
      detail: 'JSTARS (AN/APY-7 MTI radar, Ku-band), MQ-9 Lynx SAR, high-resolution SAR surveillance. JSTARS retired 2019 — UAS-based Ku SAR replacing.',
      colorHex: '#230A52' },
    { x: 468, w: 39,  row: 'bot', label: 'Rarely used',
      detail: 'K-band rarely used due to water vapour absorption. Police speed guns the main application (24.125 GHz).',
      colorHex: '#1A1D24' },
    { x: 507, w: 41,  row: 'bot', label: 'DroneShield / Fortem',
      detail: 'DroneShield DroneSentinel, Fortem TrueView F-700 Ka-band counter-UAS radar. Detects nano-UAS at >2 km. High angular resolution for target discrimination.',
      colorHex: '#2A0A5E' },
    { x: 548, w: 63,  row: 'bot', label: 'V-band comms (60G)',
      detail: '60 GHz V-band fixed wireless backhaul. O₂ absorption creates natural security zone. 802.11ad/ay WiGig short-range high-bandwidth.',
      colorHex: '#350A22' },
    { x: 611, w: 39,  row: 'bot', label: 'Collision avoidance',
      detail: '76–81 GHz automotive collision-avoidance radar (Bosch, Continental). Emerging airborne radar altimeter applications. Compact solid-state FMCW.',
      colorHex: '#3E0A1E' },
  ],
};

/* ─── Sectional groupings — tab navigation ───────────────────────────────── */

export interface BandSection {
  id: string;
  label: string;
  /** null = show all 16 tiles */
  tileIds: string[] | null;
}

export const BAND_TILE_SECTIONS: BandSection[] = [
  { id: 'all',       label: 'ALL',           tileIds: null },
  { id: 'rf',        label: 'RF',            tileIds: ['vlf', 'lf', 'mf', 'hf', 'vhf', 'uhf'] },
  { id: 'microwave', label: 'Microwave',      tileIds: ['shf', 'ehf', 'gnss'] },
  { id: 'optical',   label: 'Optical / DEW',  tileIds: ['ir', 'visible', 'uv', 'dew'] },
  { id: 'ionising',  label: 'Ionising',       tileIds: ['xray', 'gamma'] },
  { id: 'radar',     label: 'Radar',          tileIds: ['radar'] },
];

/* ─── Master export ──────────────────────────────────────────────────────── */

export const BAND_TILES: BandTile[] = [
  VLF, LF, MF, HF, VHF, UHF, SHF, EHF, GNSS,
  IR, VIS, UV, DEW, XRAY, GAMMA, RADAR,
];
