-- SPECTRAL Platform Library — Gap-fill migration
-- CLASSIFICATION: UNCLASSIFIED // FOR OFFICIAL TRAINING USE ONLY

ALTER TABLE platforms ADD COLUMN IF NOT EXISTS classification TEXT DEFAULT 'UNCLASSIFIED';

INSERT INTO platforms (
  id, name, manufacturer, country_of_origin, category,
  max_speed_kmh, service_ceiling_m, range_km, endurance_hrs, mtow_kg, warhead_kg,
  guidance_type, gnss_independent, ai_autonomous, swarm_capable,
  gnss_used, nav_backup, weapon_types, sensor_suite, known_operators, conflict_deployments,
  data_confidence, sources, classification
) VALUES
  ('punisher-uas', 'UA Dynamics Punisher', 'UA Dynamics', 'Ukraine', 'fixed_wing_tactical',
   120, 3000, 100, 4, 25, 5, 'INS+GPS', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['HE warhead']::TEXT[], ARRAY['EO']::TEXT[],
   ARRAY['Ukraine AFU']::TEXT[], ARRAY['Ukraine']::TEXT[], 'estimated',
   ARRAY['OSINT: Ukraine field reporting 2023-2024']::TEXT[], 'UNCLASSIFIED'),
  ('fpv-swarm-coord', 'Coordinated FPV Swarm', 'Field-assembled', 'Ukraine', 'FPV',
   100, 500, 15, 0.5, 2, 1.5, 'mesh', false, false, true,
   ARRAY['GPS']::TEXT[], ARRAY['visual','fibre_optic']::TEXT[], ARRAY['RPG warhead','grenade']::TEXT[], ARRAY['EO camera']::TEXT[],
   ARRAY['Ukraine AFU','Russia']::TEXT[], ARRAY['Ukraine']::TEXT[], 'estimated',
   ARRAY['OSINT: Ukraine swarm saturation reporting 2024']::TEXT[], 'UNCLASSIFIED'),
  ('uav-sx-6', 'Ukrainian Long-Range Strike UAS (SX-6 class)', 'Assessed Ukrainian industry', 'Ukraine', 'loitering_munition',
   350, 6000, 600, 3, 80, 20, 'INS+GPS', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['HE warhead']::TEXT[], ARRAY['EO']::TEXT[],
   ARRAY['Ukraine AFU']::TEXT[], ARRAY['Ukraine']::TEXT[], 'estimated',
   ARRAY['OSINT: Long-range strike reporting 2024']::TEXT[], 'UNCLASSIFIED'),
  ('bayraktar-tb3', 'Baykar TB3', 'Baykar', 'Turkey', 'MALE',
   220, 9000, 1000, 24, 1450, 120, 'INS+GPS', false, false, false,
   ARRAY['GPS','GLONASS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['precision_munitions']::TEXT[], ARRAY['EO/IR','SAR']::TEXT[],
   ARRAY['Turkey']::TEXT[], ARRAY[]::TEXT[], 'estimated',
   ARRAY['OSINT: Baykar TB3 carrier-capable MALE reporting']::TEXT[], 'UNCLASSIFIED'),
  ('songar', 'ASISGUARD Songar', 'ASISGUARD', 'Turkey', 'tactical',
   72, 3000, 10, 0.5, 25, NULL, 'INS+GPS', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS','visual']::TEXT[], ARRAY['5.56mm machine gun']::TEXT[], ARRAY['EO']::TEXT[],
   ARRAY['Turkey']::TEXT[], ARRAY[]::TEXT[], 'estimated',
   ARRAY['OSINT: ASISGUARD armed quadcopter datasheet']::TEXT[], 'UNCLASSIFIED'),
  ('zala-kyb', 'ZALA KYB', 'ZALA Aero', 'Russia', 'loitering_munition',
   110, 4000, 40, 0.5, 12, 3, 'INS+GPS', false, false, false,
   ARRAY['GPS','GLONASS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['HE warhead']::TEXT[], ARRAY['EO']::TEXT[],
   ARRAY['Russia']::TEXT[], ARRAY['Ukraine']::TEXT[], 'estimated',
   ARRAY['OSINT: ZALA KYB Ukraine combat reporting']::TEXT[], 'UNCLASSIFIED'),
  ('xq-58a-valkyrie', 'Kratos XQ-58A Valkyrie', 'Kratos', 'United States', 'fixed_wing_tactical',
   1050, 13700, 2000, 2, 2720, NULL, 'INS+GPS', false, true, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY[]::TEXT[], ARRAY['EO/IR']::TEXT[],
   ARRAY['USAF']::TEXT[], ARRAY[]::TEXT[], 'estimated',
   ARRAY['OSINT: USAF loyal wingman demonstrator']::TEXT[], 'UNCLASSIFIED'),
  ('altius-600m', 'Anduril Altius-600M', 'Anduril', 'United States', 'loitering_munition',
   185, 5500, 440, 4, 12, 4, 'INS+GPS', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['kinetic','EW','ISR']::TEXT[], ARRAY['EO/IR']::TEXT[],
   ARRAY['United States']::TEXT[], ARRAY[]::TEXT[], 'estimated',
   ARRAY['OSINT: Anduril Altius family']::TEXT[], 'UNCLASSIFIED'),
  ('fpv-rc', 'RC FPV Attack UAS', 'Field-assembled', 'Multi', 'FPV',
   100, 500, 15, 0.5, 2, 1.5, 'RF_command', false, false, false,
   ARRAY[]::TEXT[], ARRAY['visual','pilot_skill']::TEXT[], ARRAY['RPG warhead','grenade']::TEXT[], ARRAY['EO camera']::TEXT[],
   ARRAY['Ukraine AFU','Russia']::TEXT[], ARRAY['Ukraine']::TEXT[], 'estimated',
   ARRAY['OSINT: FPV saturation tactics 2023-2024']::TEXT[], 'UNCLASSIFIED'),
  ('switchblade-300', 'AeroVironment Switchblade 300', 'AeroVironment', 'United States', 'loitering_munition',
   160, 4500, 10, 0.25, 2.5, 0.5, 'INS+EO', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['HE warhead']::TEXT[], ARRAY['EO/IR']::TEXT[],
   ARRAY['United States']::TEXT[], ARRAY['Ukraine']::TEXT[], 'estimated',
   ARRAY['OSINT: AeroVironment product data']::TEXT[], 'UNCLASSIFIED'),
  ('switchblade-600', 'AeroVironment Switchblade 600', 'AeroVironment', 'United States', 'loitering_munition',
   185, 4500, 40, 0.67, 23, 6.8, 'INS+EO', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['anti-armour']::TEXT[], ARRAY['EO/IR']::TEXT[],
   ARRAY['United States']::TEXT[], ARRAY[]::TEXT[], 'estimated',
   ARRAY['OSINT: AeroVironment Switchblade 600']::TEXT[], 'UNCLASSIFIED'),
  ('hero-120', 'UVision Hero-120', 'UVision', 'Israel', 'loitering_munition',
   185, 4500, 40, 1, 12, 4.5, 'INS+EO', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['HE warhead']::TEXT[], ARRAY['EO/IR']::TEXT[],
   ARRAY['Israel']::TEXT[], ARRAY[]::TEXT[], 'estimated',
   ARRAY['OSINT: UVision Hero family']::TEXT[], 'UNCLASSIFIED'),
  ('hero-400', 'UVision Hero-400', 'UVision', 'Israel', 'loitering_munition',
   220, 5500, 150, 2, 40, 10, 'INS+EO', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['HE warhead']::TEXT[], ARRAY['EO/IR']::TEXT[],
   ARRAY['Israel']::TEXT[], ARRAY[]::TEXT[], 'estimated',
   ARRAY['OSINT: UVision Hero-400']::TEXT[], 'UNCLASSIFIED'),
  ('shahed-131', 'Shahed-131 / Geran-1', 'HESA', 'Iran', 'loitering_munition',
   180, 3000, 900, 8, 135, 12, 'INS+GPS', false, false, false,
   ARRAY['GPS','GLONASS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['HE warhead']::TEXT[], ARRAY['INS+GPS']::TEXT[],
   ARRAY['IRGC','Russian VKS']::TEXT[], ARRAY['Ukraine']::TEXT[], 'estimated',
   ARRAY['OSINT: Ukraine War tracking']::TEXT[], 'UNCLASSIFIED'),
  ('harop', 'IAI Harop', 'Israel Aerospace Industries', 'Israel', 'loitering_munition',
   185, 4570, 1000, 6, 135, 23, 'INS+EO', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS','IIR']::TEXT[], ARRAY['HE warhead']::TEXT[], ARRAY['EO/IR terminal']::TEXT[],
   ARRAY['Israel','India']::TEXT[], ARRAY['Nagorno-Karabakh']::TEXT[], 'estimated',
   ARRAY['OSINT: IAI Harop']::TEXT[], 'UNCLASSIFIED'),
  ('wb-warmate', 'WB Electronics Warmate', 'WB Electronics', 'Poland', 'loitering_munition',
   150, 4000, 30, 0.75, 4, 1.4, 'INS+GPS', false, false, false,
   ARRAY['GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['HE warhead']::TEXT[], ARRAY['EO']::TEXT[],
   ARRAY['Poland','Ukraine']::TEXT[], ARRAY['Ukraine']::TEXT[], 'estimated',
   ARRAY['OSINT: Warmate LM family']::TEXT[], 'UNCLASSIFIED'),
  ('gj-11-sharp-sword', 'Hongdu GJ-11 Sharp Sword', 'AVIC / Hongdu', 'China', 'fixed_wing_tactical',
   1000, 12500, 4000, 6, 10000, 2000, 'INS+GPS', false, true, false,
   ARRAY['BeiDou','GPS']::TEXT[], ARRAY['INS']::TEXT[], ARRAY['internal_bays']::TEXT[], ARRAY['EO/IR','SAR']::TEXT[],
   ARRAY['PLAAF']::TEXT[], ARRAY[]::TEXT[], 'estimated',
   ARRAY['OSINT: PRC stealth UCAV reporting']::TEXT[], 'UNCLASSIFIED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO anti_drone_systems (
  id, name, manufacturer, country, defeat_method, effective_range_m,
  portability, conflict_validated, data_confidence, sources
) VALUES
  ('dragonfire-uk', 'MBDA DragonFire', 'MBDA / Leonardo / QinetiQ', 'United Kingdom',
   ARRAY['laser','directed_energy']::TEXT[], 3000, 'naval', true, 'estimated',
   ARRAY['OSINT: UK MoD DragonFire demonstrator 2024']::TEXT[]),
  ('thor-hpm', 'AFRL THOR', 'US Air Force Research Laboratory', 'United States',
   ARRAY['directed_energy','microwave']::TEXT[], 2000, 'fixed', false, 'estimated',
   ARRAY['OSINT: Kirtland AFB counter-swarm HPM tests']::TEXT[]),
  ('leonidas-hpm', 'Epirus Leonidas', 'Epirus', 'United States',
   ARRAY['directed_energy','microwave']::TEXT[], 3000, 'vehicle', false, 'estimated',
   ARRAY['OSINT: Epirus Leonidas HPM product brief']::TEXT[]),
  ('morfius', 'Lockheed Martin MORFIUS', 'Lockheed Martin', 'United States',
   ARRAY['microwave','kinetic']::TEXT[], 15000, 'airborne', false, 'estimated',
   ARRAY['OSINT: MORFIUS loitering microwave concept']::TEXT[]),
  ('anduril-lattice', 'Anduril Lattice C-UAS', 'Anduril', 'United States',
   ARRAY['RF_jamming','kinetic','combined']::TEXT[], 10000, 'fixed', true, 'estimated',
   ARRAY['OSINT: Anduril Lattice networked C-UAS']::TEXT[]),
  ('lids-system', 'L3Harris LIDS', 'L3Harris', 'United States',
   ARRAY['RF_jamming','kinetic','combined']::TEXT[], 8000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: JCO LIDS integrated defeat stack']::TEXT[]),
  ('silent-archer', 'SRC Silent Archer', 'SRC Inc.', 'United States',
   ARRAY['RF_jamming']::TEXT[], 5000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: US Army Silent Archer EW C-UAS']::TEXT[]),
  ('enforceair', 'D-Fend EnforceAir', 'D-Fend Solutions', 'Israel',
   ARRAY['RF_jamming','cyber']::TEXT[], 3000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: EnforceAir RF cyber takeover C-UAS']::TEXT[]),
  ('military-ew-generic', 'Military EW Suite (generic)', 'Multi-vendor', 'Multi',
   ARRAY['RF_jamming']::TEXT[], 15000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: Training placeholder — brigade EW asset']::TEXT[]),
  ('patriot-pac-3', 'Patriot PAC-3 MSE', 'Raytheon / Lockheed Martin', 'United States',
   ARRAY['kinetic']::TEXT[], 100000, 'fixed', true, 'estimated',
   ARRAY['OSINT: PAC-3 MSE vs UAS class targets']::TEXT[]),
  ('stinger-shorad', 'FIM-92 Stinger (SHORAD)', 'Raytheon', 'United States',
   ARRAY['kinetic']::TEXT[], 4800, 'man-portable', true, 'estimated',
   ARRAY['OSINT: MANPADS vs low/slow UAS']::TEXT[]),
  ('zu-23-2', 'ZU-23-2 AAA', 'Various', 'Multi',
   ARRAY['kinetic']::TEXT[], 2500, 'vehicle', true, 'estimated',
   ARRAY['OSINT: Legacy AAA vs Shahed-class OWA']::TEXT[])
ON CONFLICT (id) DO NOTHING;

INSERT INTO defeat_effectiveness (
  platform_id, defeat_system_id, rf_jamming_pct, kinetic_pct, dew_pct,
  data_confidence, weather_limited, is_immune, immune_reason, special_notes
) VALUES
  ('kargu-2', 'coyote-block-3', NULL, 45, NULL, 'estimated', false, false, NULL, 'OSINT: kinetic Pk assessed'),
  ('kargu-2', 'military-ew-generic', 35, NULL, NULL, 'estimated', false, false, NULL, 'IR-terminal partial RF'),
  ('kargu-2', 'iron-beam', NULL, NULL, 80, 'estimated', true, false, NULL, 'DEW vs LM'),
  ('kargu-2', 'dragonfire-uk', NULL, NULL, 78, 'estimated', true, false, NULL, 'HEL vs Kargu'),
  ('uj-22-airborne', 'iris-t-slm-cuas', NULL, 70, NULL, 'estimated', false, false, NULL, 'IRIS-T SLM vs OWA'),
  ('ch-4-rainbow', 'patriot-pac-3', NULL, 75, NULL, 'estimated', false, false, NULL, 'PAC-3 vs MALE'),
  ('fpv-swarm-coord', 'lids-system', 55, 55, NULL, 'estimated', false, false, NULL, 'Layered LIDS'),
  ('fpv-swarm-coord', 'leonidas-hpm', NULL, NULL, 65, 'estimated', false, false, NULL, 'Leonidas HPM'),
  ('fpv-swarm-coord', 'morfius', NULL, NULL, 68, 'estimated', false, false, NULL, 'MORFIUS swarm'),
  ('fpv-swarm-coord', 'thor-hpm', NULL, NULL, 70, 'estimated', false, false, NULL, 'THOR HPM'),
  ('baba-yaga', 'coyote-block-3', NULL, 50, NULL, 'estimated', false, false, NULL, 'Kinetic vs hex'),
  ('shahed-136', 'dragonfire-uk', NULL, NULL, 85, 'estimated', true, false, NULL, 'DragonFire vs OWA'),
  ('shahed-136', 'iron-beam', NULL, NULL, 88, 'estimated', true, false, NULL, 'Iron Beam vs OWA'),
  ('shahed-136', 'lids-system', 55, 68, NULL, 'estimated', false, false, NULL, 'LIDS layered'),
  ('shahed-136', 'anduril-lattice', 55, 70, NULL, 'estimated', false, false, NULL, 'Lattice AI C-UAS'),
  ('shahed-136', 'silent-archer', 55, NULL, NULL, 'estimated', false, false, NULL, 'Silent Archer EW'),
  ('lancet-3', 'dragonfire-uk', NULL, NULL, 75, 'estimated', true, false, NULL, 'DragonFire vs Lancet'),
  ('lancet-3', 'iron-beam', NULL, NULL, 80, 'estimated', true, false, NULL, 'Iron Beam vs Lancet'),
  ('fpv-rc', 'dragonfire-uk', NULL, NULL, 80, 'estimated', true, false, NULL, 'DragonFire vs RC FPV'),
  ('fpv-rc', 'iron-beam', NULL, NULL, 82, 'estimated', true, false, NULL, 'Iron Beam vs RC FPV'),
  ('fpv-rc', 'lids-system', 50, 62, NULL, 'estimated', false, false, NULL, 'LIDS vs RC FPV'),
  ('fpv-rc', 'leonidas-hpm', NULL, NULL, 72, 'estimated', false, false, NULL, 'Leonidas vs RC FPV'),
  ('fpv-rc', 'enforceair', 60, NULL, NULL, 'estimated', false, false, NULL, 'EnforceAir cyber'),
  ('fpv-fibre-optic', 'enforceair', 0, NULL, NULL, 'estimated', false, true,
   'Fibre-optic FPV immune to RF cyber takeover', 'No RF C2 link')
ON CONFLICT (platform_id, defeat_system_id) DO NOTHING;
