-- Global OWA / C-UAS ORBAT tranche — Ukraine, Israel, UK, Poland, Saudi, US, India, ROK, naval, Red Sea proxies
-- OSINT training tier; confidence flagged per row

INSERT INTO anti_drone_systems (
  id, name, manufacturer, country, defeat_method, effective_range_m,
  portability, conflict_validated, data_confidence, sources, conflict_notes,
  frequency_bands_covered
) VALUES
  ('nasams-amraam-er', 'NASAMS (AMRAAM-ER C-UAS layer)', 'Kongsberg / Raytheon', 'Norway / United States',
   ARRAY['kinetic']::TEXT[], 50000, 'fixed', true, 'high',
   ARRAY['OSINT: Ukraine 2024–2026 NASAMS employment vs cruise/OWA; AMRAAM-ER range extension assessed'],
   'Point/area SAM — expensive vs Shahed exchange; layered with guns/EW',
   '{}'::jsonb),
  ('iris-t-sls-cuas', 'IRIS-T SLS (short-range vs UAS)', 'Diehl Defence', 'Germany',
   ARRAY['kinetic']::TEXT[], 8000, 'vehicle', true, 'medium',
   ARRAY['OSINT: Diehl IRIS-T SLS datasheet; Ukraine-adjacent SHORAD reporting'],
   'IRIS-T S interceptor — assessed vs Group 2–3 UAS and cruise',
   '{}'::jsonb),
  ('faad-c2-node', 'FAAD C2 (integrated C-UAS node)', 'Northrop Grumman', 'United States',
   ARRAY['combined','RF_jamming']::TEXT[], 25000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: US Army FAAD C2 — multi-sensor cueing for SHORAD/M-SHORAD'],
   'C2-only layer; defeat via linked effectors — not standalone kill',
   '{"rf_detect":"400-6000"}'::jsonb),
  ('iron-dome-tamir', 'Iron Dome (Tamir vs OWA)', 'Rafael', 'Israel',
   ARRAY['kinetic']::TEXT[], 70000, 'fixed', true, 'high',
   ARRAY['OSINT: IDF Iron Dome vs rockets/OWA; Tamir interceptor public briefings'],
   'Proven vs low-cost rockets; magazine depth vs saturation OWA waves',
   '{}'::jsonb),
  ('davids-sling-cuas', 'David''s Sling (Stunner vs OWA/cruise)', 'Rafael / Raytheon', 'Israel',
   ARRAY['kinetic']::TEXT[], 250000, 'fixed', true, 'high',
   ARRAY['OSINT: David''s Sling operational since 2017; assessed vs larger OWA'],
   'Mid-tier interceptor — overkill vs Shahed-136 but viable vs Shahed-238 class',
   '{}'::jsonb),
  ('martlet-airborne-cuas', 'Martlet (airborne C-UAS — Wildcat)', 'Thales', 'United Kingdom',
   ARRAY['kinetic']::TEXT[], 6000, 'airborne', true, 'medium',
   ARRAY['OSINT: UK MoD Wildcat Martlet trials vs UAS 2023–2025'],
   'Airborne LMM vs low/slow UAS — weather and cueing limited',
   '{}'::jsonb),
  ('land-ceptor-cuas', 'Land Ceptor (CAMM vs UAS)', 'MBDA', 'United Kingdom',
   ARRAY['kinetic']::TEXT[], 25000, 'vehicle', true, 'medium',
   ARRAY['OSINT: UK Sky Sabre / Land Ceptor — CAMM family vs air targets'],
   'CAMM soft-vertical-launch — assessed vs OWA in layered UK ORBAT',
   '{}'::jsonb),
  ('pilica-plus', 'Pilica+ (35 mm + Grom C-UAS)', 'PGZ / Mesko', 'Poland',
   ARRAY['kinetic']::TEXT[], 5500, 'fixed', true, 'estimated',
   ARRAY['OSINT: Poland Pilica+ procurement — twin 35 mm + very short SAM'],
   'Polish layered C-UAS — gun depth vs missile cost exchange',
   '{}'::jsonb),
  ('narew-camm-er', 'Narew (CAMM-ER point defence)', 'MBDA', 'Poland / United Kingdom',
   ARRAY['kinetic']::TEXT[], 45000, 'fixed', true, 'estimated',
   ARRAY['OSINT: Poland Narew programme — CAMM-ER extended range assessed'],
   'Extended-range CAMM — Ukraine-adjacent European ORBAT proxy',
   '{}'::jsonb),
  ('skyguard-laser', 'Skyguard (HEL C-UAS — Rheinmetall)', 'Rheinmetall', 'Germany',
   ARRAY['dew','kinetic']::TEXT[], 3000, 'fixed', true, 'estimated',
   ARRAY['OSINT: Rheinmetall Skyguard family — laser + 35 mm cueing demonstrations'],
   'HEL + gun combo — weather limits on laser segment',
   '{"eo_ir":"0.4-1.07"}'::jsonb),
  ('shahin-cuas', 'Shahin (C-UAS SHORAD)', 'SAMI / assessed foreign components', 'Saudi Arabia',
   ARRAY['kinetic','RF_jamming']::TEXT[], 12000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: Saudi C-UAS layering reporting 2024–2026 — Shahin class SHORAD'],
   'Gulf ORBAT proxy — layered with Patriot/NASAMS',
   '{"rf_broad":"400-6000"}'::jsonb),
  ('m-shorad-stryker', 'M-SHORAD (Stryker IM-SHORAD)', 'Leonardo DRS / RTX', 'United States',
   ARRAY['kinetic','RF_jamming','combined']::TEXT[], 5000, 'vehicle', true, 'high',
   ARRAY['OSINT: US Army M-SHORAD — Stinger, Hellfire, APKWS, Moog REK EW'],
   'Mobile SHORAD — APKWS/Stinger vs Group 1–3; EW vs RF links',
   '{"rf_broad":"400-6000"}'::jsonb),
  ('bullfrog-apkws', 'Bullfrog (APKWS C-UAS launcher)', 'L3Harris', 'United States',
   ARRAY['kinetic']::TEXT[], 6000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: L3Harris Bullfrog APKWS C-UAS launcher announcements'],
   'Truck-mounted APKWS — Ukraine-style cost-exchange lessons',
   '{}'::jsonb),
  ('akash-ng-cuas', 'Akash-NG (C-UAS / point SAM)', 'DRDO / BEL', 'India',
   ARRAY['kinetic']::TEXT[], 30000, 'vehicle', true, 'medium',
   ARRAY['OSINT: DRDO Akash-NG trials — assessed vs UAV/cruise class'],
   'Indian layered AD — mobility vs fixed site coverage',
   '{}'::jsonb),
  ('bharani-gun', 'Bharani (anti-drone gun system)', 'DRDO', 'India',
   ARRAY['kinetic']::TEXT[], 2500, 'man-portable', true, 'estimated',
   ARRAY['OSINT: DRDO Bharani anti-drone gun OSINT reporting'],
   'Soft-kill gun + cueing — short range vs FPV swarms',
   '{}'::jsonb),
  ('l-sam-cheongung', 'L-SAM / Cheongung II (C-UAS layer)', 'LIG Nex1', 'Republic of Korea',
   ARRAY['kinetic']::TEXT[], 40000, 'vehicle', true, 'medium',
   ARRAY['OSINT: ROK L-SAM programme — mid-tier interceptor public data'],
   'ROK layered AD — assessed vs OWA in peninsula scenario',
   '{}'::jsonb),
  ('sm-2-aegis-cuas', 'SM-2 (Aegis naval vs OWA)', 'Raytheon', 'United States',
   ARRAY['kinetic']::TEXT[], 170000, 'naval', true, 'high',
   ARRAY['OSINT: USN Aegis SM-2 vs anti-ship / air threats; Red Sea OWA adjudication reporting'],
   'Naval area defence — poor exchange vs cheap OWA unless layered with CIWS',
   '{}'::jsonb),
  ('sm-6-aegis-cuas', 'SM-6 (Aegis extended vs OWA/cruise)', 'Raytheon', 'United States',
   ARRAY['kinetic']::TEXT[], 240000, 'naval', true, 'high',
   ARRAY['OSINT: SM-6 dual-use reporting; assessed vs larger OWA and cruise'],
   'Overkill vs Shahed-136 — viable vs Shahed-238 / maritime OWA',
   '{}'::jsonb),
  ('pantsir-s1-cuas', 'Pantsir-S1 (C-UAS gun-missile)', 'KBP / Rostec', 'Russia',
   ARRAY['kinetic','RF_jamming']::TEXT[], 20000, 'vehicle', true, 'high',
   ARRAY['OSINT: Ukraine capture/analysis; Middle East employment vs drones'],
   '57E6 + 30 mm — confirmed drone kills; saturation and SEAD risk',
   '{"rf_broad":"400-18000"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  manufacturer = EXCLUDED.manufacturer,
  country = EXCLUDED.country,
  defeat_method = EXCLUDED.defeat_method,
  effective_range_m = EXCLUDED.effective_range_m,
  portability = EXCLUDED.portability,
  conflict_validated = EXCLUDED.conflict_validated,
  data_confidence = EXCLUDED.data_confidence,
  sources = EXCLUDED.sources,
  conflict_notes = EXCLUDED.conflict_notes,
  frequency_bands_covered = EXCLUDED.frequency_bands_covered;

INSERT INTO defeat_effectiveness (
  platform_id, defeat_system_id, rf_jamming_pct, kinetic_pct, dew_pct,
  swarm_engagement_pct, data_confidence, weather_limited, special_notes
) VALUES
  ('shahed-136', 'nasams-amraam-er', NULL, 84, NULL, 50, 'high', false,
   'Missile cost vs ~$20K OWA — not sustainable as sole layer'),
  ('shahed-136', 'iris-t-sls-cuas', NULL, 78, NULL, 55, 'medium', false, NULL),
  ('shahed-136', 'faad-c2-node', 55, NULL, NULL, 60, 'estimated', false,
   'C2 cueing — defeat via linked shooters'),
  ('shahed-136', 'iron-dome-tamir', NULL, 86, NULL, 65, 'high', false,
   'Israel — proven vs rocket/OWA class; magazine depth risk'),
  ('shahed-136', 'davids-sling-cuas', NULL, 88, NULL, 45, 'high', false,
   'Overkill interceptor — exchange ratio poor'),
  ('shahed-136', 'martlet-airborne-cuas', NULL, 70, NULL, 50, 'medium', true, NULL),
  ('shahed-136', 'land-ceptor-cuas', NULL, 80, NULL, 50, 'medium', false, NULL),
  ('shahed-136', 'pilica-plus', NULL, 81, NULL, 72, 'estimated', false,
   '35 mm + Grom — Poland layered ORBAT'),
  ('shahed-136', 'narew-camm-er', NULL, 83, NULL, 48, 'estimated', false, NULL),
  ('shahed-136', 'skyguard-laser', NULL, 65, 72, 55, 'estimated', true,
   'HEL weather-limited; gun segment backs up laser'),
  ('shahed-136', 'shahin-cuas', 50, 76, NULL, 58, 'estimated', false, NULL),
  ('shahed-136', 'm-shorad-stryker', 58, 74, NULL, 62, 'high', true,
   'APKWS/Stinger + REK jam — Ukraine lessons'),
  ('shahed-136', 'bullfrog-apkws', NULL, 75, NULL, 58, 'estimated', true, NULL),
  ('shahed-136', 'akash-ng-cuas', NULL, 79, NULL, 45, 'medium', false, NULL),
  ('shahed-136', 'bharani-gun', NULL, 68, NULL, 60, 'estimated', false,
   'Short-range gun — FPV/Group 1 bias'),
  ('shahed-136', 'l-sam-cheongung', NULL, 82, NULL, 45, 'medium', false, NULL),
  ('shahed-136', 'sm-2-aegis-cuas', NULL, 85, NULL, 40, 'high', false,
   'Naval — CIWS inner layer still required'),
  ('shahed-136', 'sm-6-aegis-cuas', NULL, 87, NULL, 38, 'high', false,
   'Extreme cost exchange vs OWA'),
  ('shahed-136', 'pantsir-s1-cuas', 45, 77, NULL, 55, 'high', false,
   'Gun-missile + RF — Ukraine-confirmed drone kills'),
  ('shahed-129', 'iron-dome-tamir', NULL, 84, NULL, 60, 'high', false, NULL),
  ('shahed-129', 'narew-camm-er', NULL, 80, NULL, 48, 'estimated', false, NULL),
  ('shahed-129', 'pantsir-s1-cuas', 42, 75, NULL, 52, 'high', false, NULL),
  ('shahed-129', 'nasams-amraam-er', NULL, 82, NULL, 48, 'high', false, NULL),
  ('shahed-238', 'davids-sling-cuas', NULL, 86, NULL, 45, 'high', false,
   'Jet OWA — higher closure speed'),
  ('shahed-238', 'sm-6-aegis-cuas', NULL, 88, NULL, 42, 'high', false, NULL),
  ('shahed-238', 'nasams-amraam-er', NULL, 80, NULL, 40, 'high', false, NULL),
  ('fpv-fibre-optic', 'pilica-plus', NULL, 78, NULL, 70, 'high', false,
   'RF silent — gun/kinetic only'),
  ('fpv-fibre-optic', 'bullfrog-apkws', NULL, 72, NULL, 55, 'medium', true, NULL),
  ('fpv-fibre-optic', 'bharani-gun', NULL, 70, NULL, 65, 'estimated', false, NULL),
  ('fpv-fibre-optic', 'm-shorad-stryker', 0, 68, NULL, 50, 'high', true,
   'EW ineffective vs fibre — kinetic/APKWS only'),
  ('samad-2', 'sm-2-aegis-cuas', NULL, 80, NULL, 45, 'high', false,
   'Red Sea maritime OWA — outer naval layer'),
  ('samad-2', 'searam', NULL, 76, NULL, 55, 'medium', false,
   'SeaRAM inner layer — HVU benchmark ~9 km')
ON CONFLICT (platform_id, defeat_system_id) DO UPDATE SET
  rf_jamming_pct = EXCLUDED.rf_jamming_pct,
  kinetic_pct = EXCLUDED.kinetic_pct,
  dew_pct = EXCLUDED.dew_pct,
  swarm_engagement_pct = EXCLUDED.swarm_engagement_pct,
  data_confidence = EXCLUDED.data_confidence,
  weather_limited = EXCLUDED.weather_limited,
  special_notes = EXCLUDED.special_notes;
