-- Gulf / global counter-UAS expansion — UAE 2026 ORBAT proxies + Shahed-proven layers
-- OSINT training tier; confidence flagged per row

INSERT INTO anti_drone_systems (
  id, name, manufacturer, country, defeat_method, effective_range_m,
  portability, conflict_validated, data_confidence, sources, conflict_notes,
  frequency_bands_covered
) VALUES
  ('edge-horizon', 'Edge Horizon EW (REACH-S class)', 'Edge Group', 'United Arab Emirates',
   ARRAY['RF_jamming','combined']::TEXT[], 12000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: Edge Group May 2026 — reported >85% drone elimination UAE'],
   'Vehicle-mounted integrated detect-jam C2; proxy for Horizon / REACH-S family',
   '{"rf_broad":"400-6000","gnss_lband":"1160-1610"}'::jsonb),
  ('ah-64e-apache-cuas', 'AH-64E Guardian (C-UAS intercept)', 'Boeing', 'United Arab Emirates',
   ARRAY['kinetic']::TEXT[], 8000, 'airborne', true, 'high',
   ARRAY['OSINT: UAE MoD Mar 2026 — Shahed intercept footage; APKWS + 30mm'],
   'Airborne counter-OWA: 30mm chain gun and APKWS laser rockets vs low/slow UAS',
   '{}'::jsonb),
  ('f-16-block60-intercept', 'F-16 Block 60 (airborne OWA intercept)', 'Lockheed Martin', 'United Arab Emirates',
   ARRAY['kinetic']::TEXT[], 15000, 'airborne', true, 'high',
   ARRAY['OSINT: UAE MoD briefing 3 Mar 2026 — fighter intercept of Shahed waves'],
   'Crewed fighter AAM intercept; high cost-exchange vs OWA — saturation risk',
   '{}'::jsonb),
  ('merops-interceptor', 'Merops drone-on-drone interceptor', 'Anduril (US deployment)', 'United States',
   ARRAY['kinetic']::TEXT[], 6000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: sUAS News Mar 2026 — US deployment Gulf after Epic Fury'],
   'AI-guided interceptor; GPS-denied navigation assessed',
   '{}'::jsonb),
  ('iron-drone-raider', 'Iron Drone Raider (net interceptor)', 'Iron Drone / Dubai Police', 'United Arab Emirates',
   ARRAY['kinetic','net']::TEXT[], 2000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: Dubai Police C-UAS integration reporting 2026'],
   'Pod-launched net capture; machine-vision lock',
   '{}'::jsonb),
  ('dronehunter-f700', 'Fortem DroneHunter F700', 'Fortem Aerospace', 'United States',
   ARRAY['kinetic','net']::TEXT[], 3000, 'vehicle', true, 'estimated',
   ARRAY['OSINT: DroneHunter F700 Drone Dome integration'],
   'Net tow-away autonomous interceptor; swarm-capable cueing',
   '{}'::jsonb),
  ('skynex', 'Rheinmetall Skynex (35 mm AHEAD)', 'Rheinmetall', 'Germany',
   ARRAY['kinetic']::TEXT[], 4000, 'vehicle', true, 'high',
   ARRAY['OSINT: Ukraine 2023–2026 Shahed/Geran swarm defeats'],
   '35 mm AHEAD programmable airburst — Ukraine-confirmed vs Shahed-136',
   '{}'::jsonb),
  ('apkws-vampire-launcher', 'L3Harris Vampire (APKWS truck)', 'L3Harris', 'United States',
   ARRAY['kinetic']::TEXT[], 6000, 'vehicle', true, 'high',
   ARRAY['OSINT: Ukraine APKWS C-UAS employment; cost-exchange vs OWA'],
   'Humvee-mounted APKWS laser-guided rockets vs Group 1–3 UAS',
   '{}'::jsonb),
  ('gepard-cuas', 'Flakpanzer Gepard (C-UAS gun)', 'Krauss-Maffei Wegmann', 'Germany',
   ARRAY['kinetic']::TEXT[], 4000, 'vehicle', true, 'high',
   ARRAY['OSINT: Ukraine Shahed defeats — twin 35 mm Oerlikon'],
   'Legacy SHORAD gun re-employed vs OWA; magazine depth limits saturation',
   '{}'::jsonb),
  ('iris-t-slm-cuas', 'IRIS-T SLM (point defence vs UAS)', 'Diehl Defence', 'Germany',
   ARRAY['kinetic']::TEXT[], 12000, 'vehicle', true, 'medium',
   ARRAY['OSINT: Ukraine/Germany air defence — assessed vs cruise/OWA'],
   'IRIS-T SL interceptor; expensive vs Shahed exchange ratio',
   '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  manufacturer = EXCLUDED.manufacturer,
  country = EXCLUDED.country,
  defeat_method = EXCLUDED.defeat_method,
  effective_range_m = EXCLUDED.effective_range_m,
  portability = EXCLUDED.portability,
  conflict_validated = EXCLUDED.conflict_validated,
  data_confidence = EXCLUDED.data_confidence,
  sources = EXCLUDED.sources,
  conflict_notes = EXCLUDED.conflict_notes,
  frequency_bands_covered = EXCLUDED.frequency_bands_covered;

-- Defeat matrix — Shahed family + FPV representative rows
INSERT INTO defeat_effectiveness (
  platform_id, defeat_system_id, rf_jamming_pct, kinetic_pct, dew_pct,
  swarm_engagement_pct, data_confidence, weather_limited, special_notes
) VALUES
  ('shahed-136', 'edge-horizon', 68, NULL, NULL, 55, 'estimated', false,
   'UAE 2026 — primary EW layer; INS-terminal Shahed reduces RF-only defeat'),
  ('shahed-136', 'ah-64e-apache-cuas', NULL, 72, NULL, 60, 'high', true,
   'MoD-released intercepts; weather/visibility limits gun/APKWS'),
  ('shahed-136', 'f-16-block60-intercept', NULL, 78, NULL, 45, 'high', true,
   'AAM intercept — poor exchange ratio at scale'),
  ('shahed-136', 'merops-interceptor', NULL, 70, NULL, 65, 'estimated', false, NULL),
  ('shahed-136', 'iron-drone-raider', NULL, 58, NULL, 50, 'estimated', false, NULL),
  ('shahed-136', 'dronehunter-f700', NULL, 62, NULL, 55, 'estimated', false, NULL),
  ('shahed-136', 'skynex', NULL, 82, NULL, 75, 'high', false,
   'Ukraine Shahed swarm — AHEAD burst kill'),
  ('shahed-136', 'apkws-vampire-launcher', NULL, 74, NULL, 60, 'high', true, NULL),
  ('shahed-136', 'gepard-cuas', NULL, 80, NULL, 70, 'high', false, NULL),
  ('shahed-136', 'iris-t-slm-cuas', NULL, 76, NULL, 40, 'medium', false,
   'Missile cost vs $20K OWA — not sustainable alone'),
  ('shahed-129', 'edge-horizon', 62, NULL, NULL, 50, 'estimated', false, NULL),
  ('shahed-129', 'ah-64e-apache-cuas', NULL, 68, NULL, 55, 'high', true, NULL),
  ('shahed-129', 'skynex', NULL, 78, NULL, 70, 'high', false, NULL),
  ('shahed-238', 'edge-horizon', 45, NULL, NULL, 35, 'estimated', false,
   'Jet OWA — higher speed reduces jam window'),
  ('shahed-238', 'f-16-block60-intercept', NULL, 82, NULL, 50, 'estimated', true, NULL),
  ('shahed-238', 'iris-t-slm-cuas', NULL, 80, NULL, 45, 'medium', false, NULL),
  ('fpv-fibre-optic', 'edge-horizon', 0, NULL, NULL, NULL, 'high', false,
   'RF silent — EW ineffective'),
  ('fpv-fibre-optic', 'ah-64e-apache-cuas', NULL, 55, NULL, 40, 'medium', true, NULL),
  ('fpv-fibre-optic', 'skynex', NULL, 75, NULL, 65, 'high', false, NULL),
  ('fpv-fibre-optic', 'iron-drone-raider', NULL, 60, NULL, 50, 'estimated', false, NULL)
ON CONFLICT (platform_id, defeat_system_id) DO UPDATE SET
  rf_jamming_pct = EXCLUDED.rf_jamming_pct,
  kinetic_pct = EXCLUDED.kinetic_pct,
  dew_pct = EXCLUDED.dew_pct,
  swarm_engagement_pct = EXCLUDED.swarm_engagement_pct,
  data_confidence = EXCLUDED.data_confidence,
  weather_limited = EXCLUDED.weather_limited,
  special_notes = EXCLUDED.special_notes;
